FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS runtime
WORKDIR /app

# Install required packages
RUN apk add --no-cache \
    icu-libs \
    tiff \
    libgdiplus \
    libc-dev \
    tzdata

# Configure globalization
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# Configure listening port
ENV ASPNETCORE_URLS=http://+:8080

# Copy published app
COPY --from=build /app/publish .

EXPOSE 8080
ENTRYPOINT ["dotnet", "CheckRide.dll"]
